import { prisma } from "../../config/prisma.js";
import { ApiError } from "../../utils/apiError.js";
import { toInt } from "../../utils/validators.js";

const ratio = (value, total) => (total ? Number((value / total).toFixed(4)) : 0);

const startOfDay = (date) => new Date(date.getFullYear(), date.getMonth(), date.getDate());
const addDays = (date, days) => {
  const next = new Date(date);
  next.setDate(next.getDate() + days);
  return next;
};
const addMonths = (date, months) => {
  const next = new Date(date);
  next.setMonth(next.getMonth() + months);
  return next;
};
const startOfWeek = (date) => {
  const start = startOfDay(date);
  const day = start.getDay();
  const mondayOffset = day === 0 ? -6 : 1 - day;
  return addDays(start, mondayOffset);
};
const startOfMonth = (date) => new Date(date.getFullYear(), date.getMonth(), 1);
const endOfMonth = (date) => addMonths(startOfMonth(date), 1);
const percentChange = (current, previous) => {
  if (!previous) return current ? 100 : 0;
  return Number((((current - previous) / previous) * 100).toFixed(1));
};
const compactText = (value, length = 64) => {
  if (!value) return "Support issue";
  return value.length > length ? `${value.slice(0, length - 1)}...` : value;
};

const endOfDay = (date) => {
  const end = startOfDay(date);
  end.setDate(end.getDate() + 1);
  return end;
};

const monthLabel = (date) => date.toLocaleString("en-US", { month: "short" });

const sanitizeFilename = (value) => String(value || "report")
  .replace(/[^a-z0-9-_]/gi, "_")
  .slice(0, 80);

const escapeCsv = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;
const escapeHtml = (value) => String(value ?? "")
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;");
const escapePdf = (value) => String(value ?? "")
  .replace(/\\/g, "\\\\")
  .replace(/\(/g, "\\(")
  .replace(/\)/g, "\\)");

const buildSimplePdf = (payload) => {
  const lines = [
    "Epson AI Helpdesk Report",
    "",
    ...Object.entries(payload).map(([key, value]) => `${key}: ${value ?? "-"}`),
  ].slice(0, 18);
  const text = lines
    .map((line, index) => `BT /F1 12 Tf 50 ${760 - index * 22} Td (${escapePdf(line)}) Tj ET`)
    .join("\n");
  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${Buffer.byteLength(text)} >> stream\n${text}\nendstream endobj`,
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf);
};

const normalizeReportPayload = (payload = {}) => ({
  "Report ID": payload.id || "RPT",
  "Report Type": payload.type || "Report",
  "Date Range": payload.dateRange || "-",
  Records: payload.records ?? 0,
  "Generated At": payload.generatedAt || new Date().toISOString(),
  "Generated By": payload.generatedBy || "Admin User",
  Status: payload.status || "COMPLETED",
});

const combineCategoryCounts = async (limit = 10) => {
  const [sessionGroups, ticketGroups] = await Promise.all([
    prisma.chatSession.groupBy({
      by: ["categoryId"],
      where: { categoryId: { not: null } },
      _count: { _all: true },
    }),
    prisma.escalationTicket.groupBy({
      by: ["categoryId"],
      where: { categoryId: { not: null } },
      _count: { _all: true },
    }),
  ]);

  const counts = new Map();
  for (const group of [...sessionGroups, ...ticketGroups]) {
    counts.set(group.categoryId, (counts.get(group.categoryId) || 0) + group._count._all);
  }

  if (!counts.size) {
    const categories = await prisma.issueCategory.findMany({
      orderBy: { name: "asc" },
      take: limit,
    });

    return categories.map((category) => ({
      categoryId: category.id,
      name: category.name,
      count: 0,
    }));
  }

  const categories = await prisma.issueCategory.findMany({
    where: { id: { in: [...counts.keys()] } },
  });

  return categories
    .map((category) => ({
      categoryId: category.id,
      name: category.name,
      count: counts.get(category.id) || 0,
    }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name))
    .slice(0, limit);
};

export const AdminService = {
  async getChatLogs(query = {}) {
    const page = Math.max(toInt(query.page, 1), 1);
    const limit = Math.min(Math.max(toInt(query.limit, 20), 1), 100);
    const dateFilter = query.date ? new Date(query.date) : null;
    const hasDateFilter = dateFilter && !Number.isNaN(dateFilter.getTime());

    const where = {
      ...(query.userId ? { userId: query.userId } : {}),
      ...(query.status ? { status: query.status } : {}),
      ...(query.categoryId ? { categoryId: query.categoryId } : {}),
      ...(hasDateFilter
        ? { updatedAt: { gte: startOfDay(dateFilter), lt: endOfDay(dateFilter) } }
        : {}),
    };

    const rows = await prisma.chatSession.findMany({
      where,
      orderBy: { updatedAt: "desc" },
      include: {
        user: { select: { id: true, employeeId: true, name: true, email: true, department: true } },
        category: true,
        messages: {
          orderBy: { createdAt: "desc" },
          take: 12,
          select: {
            id: true,
            sender: true,
            messageText: true,
            confidenceScore: true,
            createdAt: true,
          },
        },
        _count: { select: { messages: true, escalationTickets: true } },
      },
    });

    const keyword = String(query.search ?? "").trim().toLowerCase();
    const confidence = String(query.confidence ?? "").trim().toLowerCase();

    const allItems = rows
      .map((session) => {
        const latestUserMessage = session.messages.find((message) => message.sender === "USER") ?? null;
        const latestAiMessage = session.messages.find((message) => message.sender === "AI") ?? null;
        const confidenceScore = latestAiMessage?.confidenceScore ?? null;

        return {
          ...session,
          latestUserMessage,
          latestAiMessage,
          confidenceScore,
        };
      })
      .filter((session) => {
        if (!keyword) return true;

        return [
          session.title,
          session.user?.employeeId,
          session.user?.name,
          session.user?.email,
          session.category?.name,
          session.latestUserMessage?.messageText,
          session.latestAiMessage?.messageText,
        ].some((value) => String(value ?? "").toLowerCase().includes(keyword));
      })
      .filter((session) => {
        if (!confidence) return true;
        const score = session.confidenceScore;
        if (score == null) return confidence === "unknown";
        if (confidence === "high") return score >= 0.8;
        if (confidence === "medium") return score >= 0.6 && score < 0.8;
        if (confidence === "low") return score < 0.6;
        return true;
      });

    const total = allItems.length;
    const skip = (page - 1) * limit;
    const items = allItems.slice(skip, skip + limit);

    return {
      items,
      pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
    };
  },

  async getChatLogById(id) {
    const session = await prisma.chatSession.findUnique({
      where: { id },
      include: {
        user: { select: { id: true, employeeId: true, name: true, email: true, department: true } },
        category: true,
        messages: {
          orderBy: { createdAt: "asc" },
          include: { image: true },
        },
        escalationTickets: true,
      },
    });

    if (!session) throw new ApiError(404, "Chat log not found");

    const relatedKnowledge = session.categoryId
      ? await prisma.knowledgeDocument.findMany({
          where: { categoryId: session.categoryId },
          orderBy: { updatedAt: "desc" },
          take: 3,
          select: { id: true, title: true, source: true },
        })
      : [];

    return { ...session, relatedKnowledge };
  },

  async getAnalytics() {
    const now = new Date();
    const monthBuckets = Array.from({ length: 6 }, (_, index) => {
      const month = addMonths(startOfMonth(now), index - 5);
      return {
        label: monthLabel(month),
        start: month,
        end: endOfMonth(month),
      };
    });
    const weekBuckets = Array.from({ length: 5 }, (_, index) => {
      const start = addDays(startOfWeek(now), (index - 4) * 7);
      return {
        label: `Week ${index + 1}`,
        start,
        end: addDays(start, 7),
      };
    });

    const [
      totalSessions,
      resolvedSessions,
      resolvedWithoutEscalation,
      avgResponseTime,
      totalQueries,
      totalEscalations,
      escalationSnapshots,
      totalKnowledge,
      knowledgeThisMonth,
      knowledgeCoverage,
      monthlyResolutionCounts,
      monthlyEscalationCounts,
      weeklySessionCounts,
      weeklyEscalationCounts,
    ] = await Promise.all([
      prisma.chatSession.count(),
      prisma.chatSession.count({ where: { status: "RESOLVED" } }),
      prisma.chatSession.count({
        where: {
          status: "RESOLVED",
          escalationTickets: { none: {} },
        },
      }),
      prisma.chatMessage.aggregate({
        where: { sender: "AI", responseTimeMs: { not: null } },
        _avg: { responseTimeMs: true },
      }),
      prisma.chatMessage.count({ where: { sender: "USER" } }),
      prisma.escalationTicket.count(),
      prisma.escalationTicket.findMany({
        select: {
          confidenceScore: true,
          escalationReason: true,
        },
      }),
      prisma.knowledgeDocument.count(),
      prisma.knowledgeDocument.count({
        where: {
          createdAt: {
            gte: startOfMonth(now),
            lt: endOfMonth(now),
          },
        },
      }),
      prisma.knowledgeDocument.findMany({
        orderBy: { updatedAt: "desc" },
        take: 5,
        select: {
          id: true,
          title: true,
          _count: { select: { chunks: true, suggestedQuestions: true } },
        },
      }),
      Promise.all(monthBuckets.map((bucket) => (
        prisma.chatSession.count({
          where: {
            status: "RESOLVED",
            updatedAt: { gte: bucket.start, lt: bucket.end },
          },
        })
      ))),
      Promise.all(monthBuckets.map((bucket) => (
        prisma.escalationTicket.count({
          where: {
            createdAt: { gte: bucket.start, lt: bucket.end },
          },
        })
      ))),
      Promise.all(weekBuckets.map((bucket) => (
        prisma.chatSession.count({
          where: {
            createdAt: { gte: bucket.start, lt: bucket.end },
          },
        })
      ))),
      Promise.all(weekBuckets.map((bucket) => (
        prisma.escalationTicket.count({
          where: {
            createdAt: { gte: bucket.start, lt: bucket.end },
          },
        })
      ))),
    ]);

    const escalationConfidence = escalationSnapshots.reduce((acc, ticket) => {
      const score = ticket.confidenceScore;
      if (score == null) acc.noConfidence += 1;
      else if (score >= 0.8) acc.high += 1;
      else if (score >= 0.6) acc.medium += 1;
      else acc.low += 1;
      return acc;
    }, { high: 0, medium: 0, low: 0, noConfidence: 0 });

    const escalationReasons = escalationSnapshots.reduce((acc, ticket) => {
      const reason = ticket.escalationReason || "Unspecified";
      acc[reason] = (acc[reason] || 0) + 1;
      return acc;
    }, {});

    const resolutionTrend = monthBuckets.map((bucket, index) => ({
      label: bucket.label,
      resolved: monthlyResolutionCounts[index],
      escalated: monthlyEscalationCounts[index],
    }));

    const escalationRateTrend = weekBuckets.map((bucket, index) => ({
      label: bucket.label,
      sessions: weeklySessionCounts[index],
      escalations: weeklyEscalationCounts[index],
      rate: ratio(weeklyEscalationCounts[index], weeklySessionCounts[index]),
    }));

    const knowledgeUsage = knowledgeCoverage.map((document) => ({
      id: document.id,
      title: document.title,
      count: document._count.chunks,
      suggestedQuestions: document._count.suggestedQuestions,
    }));

    return {
      deflectionRate: ratio(resolvedWithoutEscalation, totalSessions),
      avgResponseTime: Math.round(avgResponseTime._avg.responseTimeMs || 0),
      totalQueries,
      resolutionRate: ratio(resolvedSessions, totalSessions),
      totalEscalations,
      totalSessions,
      totalKnowledge,
      knowledgeThisMonth,
      escalationConfidence,
      escalationReasons,
      resolutionTrend,
      escalationRateTrend,
      knowledgeUsage,
    };
  },

  exportReport(payload = {}) {
    const format = String(payload.format || "PDF").toUpperCase();
    const report = normalizeReportPayload(payload.report || payload);
    const filenameBase = sanitizeFilename(report["Report ID"]);

    if (format === "CSV") {
      const headers = Object.keys(report);
      const row = headers.map((key) => escapeCsv(report[key])).join(",");
      return {
        filename: `${filenameBase}.csv`,
        contentType: "text/csv; charset=utf-8",
        content: Buffer.from(`${headers.join(",")}\n${row}\n`),
      };
    }

    if (format === "EXCEL") {
      const rows = Object.entries(report)
        .map(([key, value]) => `<tr><th>${escapeHtml(key)}</th><td>${escapeHtml(value)}</td></tr>`)
        .join("");
      return {
        filename: `${filenameBase}.xls`,
        contentType: "application/vnd.ms-excel; charset=utf-8",
        content: Buffer.from(`<table>${rows}</table>`),
      };
    }

    return {
      filename: `${filenameBase}.pdf`,
      contentType: "application/pdf",
      content: buildSimplePdf(report),
    };
  },

  async getDashboardSummary() {
    const now = new Date();
    const todayStart = startOfDay(now);
    const tomorrowStart = addDays(todayStart, 1);
    const thisWeekStart = startOfWeek(now);
    const nextWeekStart = addDays(thisWeekStart, 7);
    const lastWeekStart = addDays(thisWeekStart, -7);
    const thisMonthStart = startOfMonth(now);
    const nextMonthStart = addMonths(thisMonthStart, 1);
    const lastMonthStart = addMonths(thisMonthStart, -1);
    const recentStart = new Date(now.getTime() - 24 * 60 * 60 * 1000);

    const [
      totalKnowledge,
      knowledgeThisMonth,
      totalSessions,
      sessionsThisWeek,
      totalEscalations,
      escalationsToday,
      escalationsThisWeek,
      escalationsLastWeek,
      resolvedSessions,
      resolvedThisMonth,
      sessionsThisMonth,
      resolvedLastMonth,
      sessionsLastMonth,
      userMessagesThisWeek,
      topIssues,
      recentDocs,
      recentTickets,
      recentSessions,
    ] = await Promise.all([
      prisma.knowledgeDocument.count(),
      prisma.knowledgeDocument.count({
        where: { createdAt: { gte: thisMonthStart, lt: nextMonthStart } },
      }),
      prisma.chatSession.count(),
      prisma.chatSession.count({
        where: { createdAt: { gte: thisWeekStart, lt: nextWeekStart } },
      }),
      prisma.escalationTicket.count(),
      prisma.escalationTicket.count({
        where: { createdAt: { gte: todayStart, lt: tomorrowStart } },
      }),
      prisma.escalationTicket.count({
        where: { createdAt: { gte: thisWeekStart, lt: nextWeekStart } },
      }),
      prisma.escalationTicket.count({
        where: { createdAt: { gte: lastWeekStart, lt: thisWeekStart } },
      }),
      prisma.chatSession.count({ where: { status: "RESOLVED" } }),
      prisma.chatSession.count({
        where: { status: "RESOLVED", createdAt: { gte: thisMonthStart, lt: nextMonthStart } },
      }),
      prisma.chatSession.count({
        where: { createdAt: { gte: thisMonthStart, lt: nextMonthStart } },
      }),
      prisma.chatSession.count({
        where: { status: "RESOLVED", createdAt: { gte: lastMonthStart, lt: thisMonthStart } },
      }),
      prisma.chatSession.count({
        where: { createdAt: { gte: lastMonthStart, lt: thisMonthStart } },
      }),
      prisma.chatMessage.findMany({
        where: {
          sender: "USER",
          createdAt: { gte: thisWeekStart, lt: nextWeekStart },
        },
        select: { createdAt: true },
      }),
      combineCategoryCounts(6),
      prisma.knowledgeDocument.findMany({
        where: { updatedAt: { gte: recentStart } },
        orderBy: { updatedAt: "desc" },
        take: 5,
        select: { id: true, title: true, createdAt: true, updatedAt: true },
      }),
      prisma.escalationTicket.findMany({
        where: { createdAt: { gte: recentStart } },
        orderBy: { createdAt: "desc" },
        take: 5,
        include: {
          user: { select: { employeeId: true, name: true } },
          category: { select: { name: true } },
        },
      }),
      prisma.chatSession.findMany({
        where: { updatedAt: { gte: recentStart } },
        orderBy: { updatedAt: "desc" },
        take: 5,
        include: {
          user: { select: { employeeId: true, name: true } },
          category: { select: { name: true } },
          _count: { select: { escalationTickets: true } },
        },
      }),
    ]);

    const dailyChatVolume = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((label) => ({
      label,
      count: 0,
    }));

    for (const message of userMessagesThisWeek) {
      const day = message.createdAt.getDay();
      const mondayIndex = day === 0 ? 6 : day - 1;
      dailyChatVolume[mondayIndex].count += 1;
    }

    const resolutionRate = ratio(resolvedSessions, totalSessions);
    const thisMonthResolutionRate = ratio(resolvedThisMonth, sessionsThisMonth);
    const lastMonthResolutionRate = ratio(resolvedLastMonth, sessionsLastMonth);

    const docActivities = recentDocs.map((doc) => ({
      type: "knowledge",
      title: `${doc.createdAt.getTime() === doc.updatedAt.getTime() ? "New KB Article" : "Updated KB"}: ${doc.title}`,
      actor: "Admin",
      occurredAt: doc.updatedAt,
      icon: "fa-book-open",
      tone: "blue",
    }));

    const ticketActivities = recentTickets.map((ticket) => ({
      type: "ticket",
      title: `Escalated: ${ticket.category?.name ?? compactText(ticket.summary)}`,
      actor: ticket.user?.employeeId ?? ticket.user?.name ?? "User",
      occurredAt: ticket.createdAt,
      icon: "fa-triangle-exclamation",
      tone: "orange",
    }));

    const sessionActivities = recentSessions
      .filter((session) => session.status === "RESOLVED" || session._count.escalationTickets === 0)
      .map((session) => ({
        type: "chat",
        title: session.status === "RESOLVED"
          ? `Resolved chat: ${session.category?.name ?? compactText(session.title)}`
          : `Chat session: ${compactText(session.title)}`,
        actor: session.user?.employeeId ?? session.user?.name ?? "User",
        occurredAt: session.updatedAt,
        icon: session.status === "RESOLVED" ? "fa-circle-check" : "fa-comments",
        tone: "green",
      }));

    const recentActivity = [...docActivities, ...ticketActivities, ...sessionActivities]
      .sort((a, b) => b.occurredAt.getTime() - a.occurredAt.getTime())
      .slice(0, 5);

    return {
      stats: {
        knowledge: {
          total: totalKnowledge,
          thisMonth: knowledgeThisMonth,
        },
        sessions: {
          total: totalSessions,
          thisWeek: sessionsThisWeek,
        },
        escalations: {
          total: totalEscalations,
          today: escalationsToday,
        },
        resolution: {
          rate: resolutionRate,
          deltaVsLastMonth: Number(((thisMonthResolutionRate - lastMonthResolutionRate) * 100).toFixed(1)),
        },
      },
      commonIssues: topIssues,
      dailyChatVolume,
      escalationTrend: {
        thisWeek: escalationsThisWeek,
        lastWeek: escalationsLastWeek,
        changePercent: percentChange(escalationsThisWeek, escalationsLastWeek),
      },
      recentActivity,
    };
  },

  getTopIssues: combineCategoryCounts,
};
